- name: Converge
  hosts: all
  become: true
  vars:
    http_checker_image_repository: imm174/http-checker
    http_checker_image_tag: "1.0.0"
    http_checker_status_codes: [200]
  roles:
    - role: http_checker
